server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: between_route
          uri: https://httpbin.org
          predicates:
            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]