spring:
  application:
    name: circuit-breaker
  profiles:
    active: turbine
server:
  port: 8080
---
spring:
  profiles: hystrix
management:
  endpoints:
    web:
      exposure:
        include: '*' # 开启对hystrix.stream的访问监控
---
spring:
  profiles: turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
turbine:
  combine-host-port: true # 可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，这会使得在本机调试的时候，本机上的不同服务聚合成一个服务来统计。
  app-config: circuit-breaker,circuit-breaker2 # 配置监控服务的列表，表明监控哪些服务多个使用","分割
  cluster-name-expression: metadata['cluster']
  aggregator:
    cluster-config: default
  instanceUrlSuffix: /hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: '*' # 开启对hystrix.stream的访问监控
