spring:
  application:
    name: eureka-server
  profiles:
    active: standalone
server:
  port: 8761
---
# standalone mode
spring:
  profiles: standalone
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
# two peer awareness
spring:
  profiles: peer1
eureka:
  instance:
    hostname: 118.118.116.63
  client:
    serviceUrl:
      defaultZone: http://118.118.116.142:8761/eureka/
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: 118.118.116.142
  client:
    serviceUrl:
      defaultZone: http://118.118.116.63:8761/eureka/
---
### three peer awareness
spring:
  profiles: cluster
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer3/eureka/,http://peer4/eureka/,http://peer5/eureka/
---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
---
spring:
  profiles: peer4
eureka:
  instance:
    hostname: peer4
---
spring:
  profiles: peer5
eureka:
  instance:
    hostname: peer5
---
# securing mode
spring:
  profiles: secure
  security:
    user:
      name: user
      password: password
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/