server:
  port: 7070

spring:
  application:
    name: nacos-config-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    config:
      server:
        git:
          uri: https://github.com/fangjian0423/blogimages
          search-paths: /
