server:
  port: 8888
spring:
  application:
    name: robbin-load-balancing

say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000 # 15s